# Assignment Day 1
## By AKash Nauhwar

# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.37093451 0.47405559 0.95564341]
  [0.21389583 0.00193798 0.06715774]
  [0.72014672 0.13062591 0.71015621]]

 [[0.19787085 0.93471842 0.42008274]
  [0.17634319 0.71700438 0.97376445]
  [0.2474614  0.57278938 0.66204474]]

 [[0.15565777 0.9111596  0.5401878 ]
  [0.39923568 0.24504606 0.27766822]
  [0.04578476 0.76615826 0.34607583]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.70780851 0.72290431 0.75131379 0.82029919 0.6611311 ]
 [0.52167122 0.95558705 1.         0.32996643 0.79620381]
 [0.76371988 0.79493468 0.82293406 0.88844472 0.49453704]
 [0.2076393  0.59825512 0.9610006  0.32484092 0.32262109]
 [0.         0.22231047 0.9043144  0.31841743 0.49781548]]


# 5.  How to find common values between two arrays?

In [5]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [7]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 0 1 1 1]
Second array:
[1 1 1 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.20254083 0.24384277 0.41250152 0.70380063 0.47231821 0.
 0.87517967 0.13770806 0.72837027 0.74950913]


# 9. How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=0)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y


array([[-0.34782129,  0.04264949,  0.44644784, ..., -0.14428102,
        -0.11711791, -0.11605835],
       [ 0.4217654 ,  0.32068866, -0.37816523, ...,  0.00417528,
         0.34263234, -0.09729683],
       [ 0.28326639,  0.40736709, -0.30164534, ..., -0.2541013 ,
         0.07559242,  0.01663875],
       [ 0.28715433, -0.32128192,  0.03659409, ...,  0.37365666,
         0.12505464,  0.38899018],
       [-0.06254066,  0.19503309,  0.13935683, ...,  0.19051835,
         0.18788892, -0.41039378]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[2. 3. 2. ... 4. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [12]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([87, 84, 89])

# 13.How to find the most frequent value in an array?

In [13]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[7 9 4 ... 3 6 1]
rank: 4


# 14.How to get the n largest values of an array

In [14]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


# 15.How to create a record array from a regular array?

In [15]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
